#! /usr/bin/env python3

import sys
import webbrowser

query = sys.argv[-1]
baseUrl = 'https://www.google.com/search?q={}'.format(query)

print('Opening default browser...')
print('Searching Google for "{}"'.format(query))

if __name__ == '__main__':
    webbrowser.open_new(baseUrl)


